server:
  port: 8280

spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_1?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nhn_academy_1
    password: ubfQOVGF7nAp$$OE
#    변경내용 무시된 상태 해제 커맨드 : git update-index --no-assume-unchanged src/main/resources/application-dev.yml
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

    dbcp2:
      initial-size: 5                  # 초기 커넥션 수
      max-total: 20                    # 최대 커넥션 수
      max-idle: 10                     # 유휴 상태에서 최대 커넥션 수
      min-idle: 5                      # 유휴 상태에서 최소 커넥션 수
      validation-query: SELECT 1       # 연결 유효성 검사 쿼리
      test-on-borrow: true             # 풀에서 가져올 때 유효성 검사
      test-while-idle: true            # 유휴 상태에서 유효성 검사

  sql:
    init:
      mode: always
  web:
    resources:
      static-locations: file:upload/

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # 파일 크기 제한
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379      #각자 쓰고있는 포트에 따라 변경
      database: 0
      username:
      password:

  rabbitmq:
    virtual-host: vh1_dev